flask:
    port: 80
    debug: true
    host: where.ranman.org
    base_url: http://where.ranman.org

foursquare:
    client_id: 0
    client_secret: 0
    redirect_uri: /oauth/foursquare/authorize

facebook: 0


twitter: 0


github: 0


dropbox: 0
